apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  name: myapp-ingress
spec:
  rules:          # routing rules are specified
   - host: myapp.com    # request coming to this host should be forwarded to serviveName
     http:             # incoming request gets forwarded to internal service
       paths:         # url path
        - path: /dashboard    
            backend:
              serviceName: myapp-internal-dashboard-service    # receives forwarded request from host
              servicePort: 8080
        - path: /login
            backend:
              serviceName: myapp-internal-login-service    # receives forwarded request from host
              servicePort: 8080
