apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3 # Desired number of pods
  selector:
    app: nginx # Labels to identify managed pods
  template:
    metadata:
      labels:
        app: nginx # Pods with this label are managed
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
