apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:       # actual contents in key-value pairs        
  database_url: mongodb-internal-serv      # is nothing but the service(internal) name of mongodb
