apiversion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress-deploy'
  labels:
    app: mongoexpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongoexpress
    template:
      metadata:
        labels:
          app: mongoexpress
      spec:
        containers:
          - name: mongo-express
            image: mongo-express
            ports:
             - containerPort: 8081
            env:
             - name: ME_CONFIG_MONGODB_ADMINUSERNAME
               valueFrom:
                 secretKeyRef:
                   name: mongodb-secret    # name of the secret created
                   key: username           # this value is from data section of secret.yaml
             - name: ME_CONFIG_MONGODB_ADMINPASSWORD
               valueFrom:
                 secretKeyRef:
                   name: mongodb-secret    # name of the secret created
                   key: password           # this value is from data section of secret.yaml
              - name: ME_CONFIG_MONGODB_SERVER
                value:
                 
             
